# File: nixpacks.toml
# Konfigurasi ini memberitahu Railway bagaimana cara membangun lingkungan untuk aplikasi Laravel Anda.

# Fase "setup" dijalankan sebelum proses build utama.
[phases.setup]
aptPkgs = [
    "ghostscript", 
    "ffmpeg",
    "libmagickwand-dev"
]

# Fase "build" adalah saat Railway menjalankan perintah seperti 'composer install'.
[phases.build]
cmds = [
    "composer install --no-dev --optimize-autoloader"
]

# Di sini kita mendefinisikan variabel lingkungan khusus untuk proses build Nixpacks.
[variables]
# Daftarkan semua ekstensi PHP yang dibutuhkan oleh proyek Anda.
NIXPACKS_PHP_EXTENSIONS = "bcmath,exif,gd,imagick,pdo_mysql,zip"

# Mengatur batas memori, ukuran upload, dan ukuran post.
NIXPACKS_PHP_INI_MEMORY_LIMIT = "1024M"
NIXPACKS_PHP_INI_UPLOAD_MAX_FILESIZE = "500M"
NIXPACKS_PHP_INI_POST_MAX_SIZE = "512M"


# --- PERBAIKAN: Bagian [start] dihapus ---
# Kita membiarkan Nixpacks menggunakan server produksi defaultnya (Nginx + PHP-FPM)
# yang akan menghormati pengaturan di atas, tidak lagi menggunakan 'php artisan serve'.

