# File: nixpacks.toml
# Versi final yang menggunakan file konfigurasi Nginx kustom.

# Fase "setup" menginstal program yang dibutuhkan.
[phases.setup]
aptPkgs = [
    "ghostscript", 
    "ffmpeg",
    "libmagickwand-dev"
]

# Fase "build" menjalankan semua perintah build secara berurutan.
[phases.build]
cmds = [
    "composer install --no-dev --optimize-autoloader",
    "npm install",
    "npm run build",
    "php artisan storage:link"
]

# Variabel untuk mengonfigurasi PHP dan Nginx.
[variables]
# Ekstensi PHP yang dibutuhkan.
NIXPACKS_PHP_EXTENSIONS = "bcmath,exif,gd,imagick,pdo_mysql,zip"

# Konfigurasi batas untuk PHP.
NIXPACKS_PHP_INI_MEMORY_LIMIT = "1024M"
NIXPACKS_PHP_INI_UPLOAD_MAX_FILESIZE = "500M"
NIXPACKS_PHP_INI_POST_MAX_SIZE = "512M"

# --- PERBAIKAN FINAL: Menggunakan File Konfigurasi Nginx Kustom ---
# Memberitahu Nixpacks untuk menggunakan file konfigurasi Nginx kita.
# Path ini relatif terhadap root proyek Anda.
NIXPACKS_NGINX_CUSTOM_CONF_FILE = "./config/nginx/nginx.conf"

# Kita tidak lagi memerlukan variabel NIXPACKS_NGINX_CLIENT_MAX_BODY_SIZE
# karena sudah diatur di dalam file .conf
