# File: nixpacks.toml
# Konfigurasi ini adalah SATU-SATUNYA sumber kebenaran untuk build di Railway.

# Fase "setup" menginstal program yang dibutuhkan.
[phases.setup]
aptPkgs = [
    "ghostscript", 
    "ffmpeg",
    "libmagickwand-dev"
]

# Fase "build" menjalankan semua perintah build secara berurutan.
[phases.build]
cmds = [
    "composer install --no-dev --optimize-autoloader",
    "npm install",
    "npm run build",
    "php artisan storage:link"
]

# Variabel untuk mengonfigurasi PHP dan Nginx.
[variables]
# Ekstensi PHP yang dibutuhkan.
NIXPACKS_PHP_EXTENSIONS = "bcmath,exif,gd,imagick,pdo_mysql,zip"

# Konfigurasi batas untuk PHP.
NIXPACKS_PHP_INI_MEMORY_LIMIT = "1024M"
NIXPACKS_PHP_INI_UPLOAD_MAX_FILESIZE = "500M"
NIXPACKS_PHP_INI_POST_MAX_SIZE = "512M"

# Konfigurasi batas untuk Nginx (untuk error 413).
NIXPACKS_NGINX_CLIENT_MAX_BODY_SIZE = "512M"

# --- Bagian [start] sengaja dihapus ---
# Membiarkan Nixpacks menggunakan server produksi default (Nginx + PHP-FPM).
