# File: nixpacks.toml
# Konfigurasi ini memberitahu Railway bagaimana cara membangun lingkungan untuk aplikasi Laravel Anda.

# Fase "setup" dijalankan sebelum proses build utama.
# Di sini kita menginstal paket-paket sistem yang dibutuhkan oleh aplikasi kita.
[phases.setup]
aptPkgs = [
    # Wajib untuk kompresi PDF.
    "ghostscript", 

    # Wajib untuk kompresi video dan audio.
    "ffmpeg",

    # Wajib agar ekstensi PHP 'imagick' bisa berfungsi dengan baik.
    "libmagickwand-dev"
]

# Fase "build" adalah saat Railway menjalankan perintah seperti 'composer install'.
[phases.build]
cmds = [
    "composer install --no-dev --optimize-autoloader"
]

# Di sini kita mendefinisikan variabel lingkungan khusus untuk proses build Nixpacks.
[variables]
# Daftarkan semua ekstensi PHP yang dibutuhkan oleh proyek Anda.
# Nixpacks akan memastikan semua ekstensi ini aktif.
NIXPACKS_PHP_EXTENSIONS = [
    "bcmath",
    "exif",
    "gd",       # Diperlukan oleh Intervention Image (Driver default)
    "imagick",  # Diperlukan oleh Intervention Image (Driver yang lebih efisien)
    "pdo_mysql",# Untuk koneksi database MySQL/MariaDB
    "zip"       # Untuk membuat file .zip
]

# Perintah yang dijalankan saat aplikasi dimulai.
[start]
cmd = "php artisan serve --host 0.0.0.0 --port $PORT"
